version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: workout_wojtur
    environment:
      POSTGRES_DB: workout_wojtur
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
