spring:
  datasource:
    url: test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

security:
  jwt:
    secret-key: test
    expiration-time: 3600000


