spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workout_wojtur
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 6db8a64a2e5319
    password: 847d7969d0cb17
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

security:
  jwt:
    secret-key: itsmysecretkeywithlengthgreaterthan256bitsanditsverysecure
    expiration-time: 3600000

logging:
  level:
    org:
      hibernate:
        engine:
          internal:
            StatefulPersistenceContext: ERROR



