name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Generate Swagger Code
        run: gradle generateSwaggerCodeWorkoutTrackerApi

      - name: Build with Gradle
        run: gradle clean build

      - name: Upload artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          source: "build/libs/WorkoutTracker-*.jar"
          target: "/home"

      - name: Restart Application on VPS
        env:
          VPS_USER: ${{ secrets.SERVER_USER }}
          VPS_HOST: ${{ secrets.SERVER_IP }}
        run: |
          ssh $VPS_USER@$VPS_HOST << 'EOF'
          sudo systemctl restart workouttracker.service
          EOF
