name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.SERVER_USER }}
          VPS_HOST: ${{ secrets.SERVER_IP }}
        run: |
          ssh $VPS_USER@$VPS_HOST << 'EOF'
          cd /home
          git pull origin main
          cd /home/WorkoutTracker/build/libs
          gradle build
          sudo systemctl restart workouttracker.service
          EOF
