name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

      - name: Deploy to VPS
        env:
          VPS_USER: root
          VPS_HOST: 188.68.247.208
          VPS_PATH: /home
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
          cd $VPS_PATH
          git pull origin main
          ./gradlew build
          sudo systemctl restart workouttracker.service
          EOF
